Repository InnoSWP/b21-02-anonymous-feedback, pull requests merged in 2022-06, with the labels that each got.

#35 Prepare the initial GraphQL schema
  backend/schema.graphql
Labels: area: website, area: backend

#41 Initialize frontend
  frontend/.gitignore
  frontend/.gitkeep
  frontend/package-lock.json
  frontend/package.json
  frontend/public/index.html
  frontend/src/App/index.tsx
  frontend/src/index.tsx
  frontend/src/react-app-env.d.ts
  frontend/tsconfig.json
Labels: type: meta, area: website

#42 Implement the sign-in screen
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App/index.tsx
  frontend/src/App/style.scss
  frontend/src/Button/index.tsx
  frontend/src/Button/style.scss
  frontend/src/Wrapper/index.tsx
  frontend/src/Wrapper/style.scss
  frontend/src/colors.scss
  frontend/src/index.tsx
  frontend/src/landing/Landing/background/background@2k.avif
  frontend/src/landing/Landing/background/background@2k.jpg
  frontend/src/landing/Landing/background/background@2k.webp
  frontend/src/landing/Landing/background/background@4k.avif
  frontend/src/landing/Landing/background/background@4k.jpg
  frontend/src/landing/Landing/background/background@4k.webp
  frontend/src/landing/Landing/index.tsx
  frontend/src/landing/Landing/style.scss
  frontend/src/landing/SignIn/index.tsx
  frontend/src/landing/SignIn/style.scss
Labels: area: website

#43 Implement "Create a guest session" screen
  frontend/package.json
  frontend/src/App/index.tsx
  frontend/src/App/style.scss
  frontend/src/Button/index.tsx
  frontend/src/Button/style.scss
  frontend/src/IconButton/index.tsx
  frontend/src/IconButton/style.scss
  frontend/src/TextInput/index.tsx
  frontend/src/TextInput/style.scss
  frontend/src/colors.scss
  frontend/src/icons/backArrow.svg
  frontend/src/index.tsx
  frontend/src/landing/NewSession/index.tsx
  frontend/src/landing/NewSession/style.scss
  frontend/src/landing/NewSession/useCreateSession.tsx
  frontend/src/landing/SignIn/index.tsx
Labels: area: website

#44 Feedback session screen
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App/index.tsx
  frontend/src/App/style.scss
  frontend/src/client.tsx
  frontend/src/index.tsx
  frontend/src/session/Session/index.tsx
  frontend/src/session/Session/style.scss
  frontend/src/session/Session/useSession.tsx
  frontend/src/session/SessionView/Connected/index.tsx
  frontend/src/session/SessionView/Connected/style.scss
  frontend/src/session/SessionView/Message/index.tsx
  frontend/src/session/SessionView/Message/style.scss
  frontend/src/session/SessionView/Message/useDisplayAge.tsx
  frontend/src/session/SessionView/Messages/index.tsx
  frontend/src/session/SessionView/Messages/style.scss
  frontend/src/session/SessionView/NoMessages/index.tsx
  frontend/src/session/SessionView/NoMessages/style.scss
  frontend/src/session/SessionView/index.tsx
  frontend/src/session/SessionView/style.scss
  frontend/src/types.tsx
  frontend/tsconfig.json
Labels: area: website

#45 Fix GraphQL schema
  backend/schema.graphql
  backend/schema.py
  frontend/src/session/Session/useSession.tsx
  frontend/src/session/SessionView/Message/index.tsx
  frontend/src/types.tsx
Labels: type: bug, area: website, area: backend

#46 Results of the week 3
  .gitignore
  README.md
  backend/Dockerfile
  backend/__init__.py
  backend/config.py
  backend/main.py
  backend/requirements.txt
  backend/schema.py
  bot/Dockerfile
  bot/__init__.py
  bot/config.py
  bot/main.py
  bot/requirements.txt
  db/__init__.py
  db/init_db.py
  db/models.py
  docker-compose.yaml
  example.env
Labels: area: backend

#60 Fix web socket connections over HTTPS
  frontend/src/client.tsx
Labels: type: bug

#64 Continuous Integration
  .github/workflows/main.yml
Labels: area: devops

#67 Session controls
  frontend/src/Button/index.tsx
  frontend/src/session/SessionView/index.tsx
  frontend/src/session/SessionView/style.scss
Labels: type: enhancement

#69 Implement notifications
  frontend/src/react-app-env.d.ts
  frontend/src/session/Session/notification.ogg
  frontend/src/session/Session/notify.tsx
  frontend/src/session/Session/useSession.tsx
  frontend/src/session/SessionView/index.tsx
  frontend/src/session/SessionView/useNotificationPermission.tsx
Labels: area: website

#71 Replace the wallpaper on the landing page
  frontend/src/landing/Landing/background/background@2k.avif
  frontend/src/landing/Landing/background/background@2k.jpg
  frontend/src/landing/Landing/background/background@2k.webp
  frontend/src/landing/Landing/background/background@4k.avif
  frontend/src/landing/Landing/background/background@4k.jpg
  frontend/src/landing/Landing/background/background@4k.webp
Labels: type: enhancement, area: website

#74 Update proxy port
  frontend/package.json
Labels: area: website

#73 Don't open `db`'s 5432 port
  docker-compose.yaml
Labels: area: devops

#72 Replace the notification sound
  frontend/src/react-app-env.d.ts
  frontend/src/session/Session/notification.ogg
  frontend/src/session/Session/notification.wav
  frontend/src/session/Session/notify.tsx
Labels: type: enhancement, area: website

#70 Disable "create the session" button for empty session names
  frontend/src/TextInput/index.tsx
  frontend/src/TextInput/style.scss
  frontend/src/landing/NewSession/index.tsx
Labels: type: bug, area: website

#85 Backend tests
  backend/Dockerfile
  backend/config.py
  backend/main.py
  backend/requirements.txt
  backend/tests/conftest.py
  backend/tests/helpers.py
  backend/tests/queries.py
  backend/tests/test_graphql.py
  bot/Dockerfile
  docker-compose.yaml
  frontend/Dockerfile
Labels: area: backend, area: devops

#87 Backend test coverage
  .githooks/pre-commit
  backend/.coveragerc
  backend/Dockerfile
  backend/schema.py
Labels: area: backend, area: devops

#88 Implement unit tests on frontend 🤡
  .github/workflows/linter.yml
  .github/workflows/test.yml
  frontend/package-lock.json
  frontend/package.json
  frontend/src/Button/Button.test.tsx
  frontend/src/IconButton/IconButton.test.tsx
  frontend/src/TextInput/TextInput.test.tsx
  frontend/src/landing/NewSession/NewSession.test.tsx
  frontend/src/landing/NewSession/useCreateSession.tsx
  frontend/src/landing/SignIn/SignIn.test.tsx
  frontend/src/session/SessionView/Message/Message.test.tsx
  frontend/src/session/SessionView/Messages/Messages.test.tsx
  frontend/src/session/SessionView/SessionView.test.tsx
Labels: area: website

#91 Add a license & write a readme
  LICENSE
  README.md
  screenshots/landingPage.png
  screenshots/sessionPage.png
Labels: type: meta

#93 Prepare the GraphQL schema for Week 6
  backend/schema.graphql
Labels: type: enhancement, area: website, area: backend

#101 Migrate to Redis state storage
  .gitignore
  bot/config.py
  bot/main.py
  bot/requirements.txt
  docker-compose.yaml
Labels: area: bot

#105 Backend rating messages
  README.md
  backend/schema.py
  backend/tests/helpers.py
  backend/tests/queries.py
  backend/tests/test_graphql.py
  db/models.py
Labels: area: backend

#104 Session closing on backend side
  backend/schema.py
  backend/tests/helpers.py
  backend/tests/queries.py
  backend/tests/test_graphql.py
Labels: area: backend

#107 Update `Message` type definition
  frontend/src/session/SessionView/Message/Message.test.tsx
  frontend/src/session/SessionView/Message/index.tsx
  frontend/src/session/SessionView/Messages/Messages.test.tsx
  frontend/src/session/SessionView/SessionView.test.tsx
  frontend/src/session/useManageSession/notify.tsx
  frontend/src/session/useManageSession/types.tsx
  frontend/src/session/useManageSession/useQuerySession.tsx
  frontend/src/session/useManageSession/useWatchMessages.tsx
  frontend/src/session/useManageSession/utils.tsx
  frontend/src/types.tsx
Labels: area: website

#108 Export sessions
  frontend/package-lock.json
  frontend/package.json
  frontend/src/downloadFile.tsx
  frontend/src/index.tsx
  frontend/src/polyfillBuffer.tsx
  frontend/src/session/Session/index.tsx
  frontend/src/session/SessionClosed/index.tsx
  frontend/src/session/SessionClosed/style.scss
  frontend/src/session/SessionView/Message/index.tsx
  frontend/src/session/SessionView/Messages/index.tsx
  frontend/src/session/SessionView/SessionView.test.tsx
  frontend/src/session/SessionView/index.tsx
  frontend/src/session/generateCsv.tsx
  frontend/src/session/types.tsx
  frontend/src/session/useManageSession/index.tsx
  frontend/src/session/useManageSession/notify.tsx
  frontend/src/session/useManageSession/useCloseSession.tsx
  frontend/src/session/useManageSession/useQuerySession.tsx
  frontend/src/session/useManageSession/useWatchMessages.tsx
  frontend/src/session/utils.tsx
Labels: area: website

#109 Added Bot star rating
  bot/main.py
Labels: area: bot

#100 Fix Docker Compose configuration
  docker-compose.yaml
Labels: area: devops

#112 Implement rating on frontend
  frontend/src/session/SessionView/Message/index.tsx
  frontend/src/session/SessionView/Rating/Star.tsx
  frontend/src/session/SessionView/Rating/index.tsx
  frontend/src/session/SessionView/Rating/style.scss
  frontend/src/session/SessionView/SessionView.test.tsx
  frontend/src/session/SessionView/index.tsx
  frontend/src/session/SessionView/style.scss
  frontend/src/session/generateCsv.tsx
  frontend/src/session/types.tsx
  frontend/src/session/useManageSession/index.tsx
  frontend/src/session/useManageSession/useAverageRating.tsx
Labels: area: website

#113 Confirm if the user intended to close the session
  frontend/src/session/SessionView/index.tsx
Labels: area: website
